//package OA;

import java.io.IOError;

//public class TestTryCatch {
//    public static void main(String[] args) {
//        try{
//            System.out.println("A");
//            badMethod();
//            System.out.println("B");
//        }catch (Exception ex){
//            System.out.println("c");
//        }finally {
//            System.out.println("D");
//        }
//    }
//    public static void badMethod() {
//        throw new Error(); // 18 行有错误。 Error 用来jvm的错误，人为无法修复的
//    }

//    public static void main(String[] args) {
//        try{
//            System.out.println("Hello World");
//        }catch (Exception e){
//            System.out.println("e");
//        }catch (ArithmeticException e){ // will not compile
//            System.out.println("e");
//        }finally {
//            System.out.println("!");
//        }
//    }
//}


